/** Design system: "Precision Hire" — AI Recruitment Intelligence.
 *  Enterprise analytical aesthetic with recruitment-specific tokens. */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        primary: 'var(--primary)',
        'on-primary': 'var(--on-primary)',
        secondary: 'var(--secondary)',
        accent: 'var(--accent)',
        support: 'var(--support)',
        info: 'var(--info)',
        danger: 'var(--danger)',
        background: 'var(--background)',
        foreground: 'var(--foreground)',
        muted: 'var(--muted)',
        border: 'var(--border)',
        destructive: 'var(--danger)',
        success: 'var(--accent)',
        warning: 'var(--support)',
        ring: 'var(--primary)',
        surface: 'var(--surface)',
        'surface-hover': 'var(--surface-hover)',
        'surface-elevated': 'var(--surface-elevated)',
        sidebar: 'var(--sidebar)',
        tertiary: 'var(--info)',
      },
      fontFamily: {
        heading: ['"Inter"', 'system-ui', 'sans-serif'],
        body: ['"Inter"', 'system-ui', 'sans-serif'],
        mono: ['"IBM Plex Mono"', '"JetBrains Mono"', 'monospace'],
      },
      fontSize: {
        'display-lg': ['36px', { lineHeight: '1.15', letterSpacing: '-0.03em', fontWeight: '700' }],
        'display-md': ['28px', { lineHeight: '1.2', letterSpacing: '-0.025em', fontWeight: '700' }],
        'heading-lg': ['22px', { lineHeight: '1.3', letterSpacing: '-0.015em', fontWeight: '600' }],
        'heading-md': ['18px', { lineHeight: '1.35', letterSpacing: '-0.01em', fontWeight: '600' }],
        'heading-sm': ['15px', { lineHeight: '1.4', letterSpacing: '0', fontWeight: '600' }],
        'body-lg': ['15px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.55', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '1.5', letterSpacing: '0.005em', fontWeight: '400' }],
        'caption': ['12px', { lineHeight: '1.4', letterSpacing: '0.01em', fontWeight: '500' }],
        'label': ['11px', { lineHeight: '1', letterSpacing: '0.06em', fontWeight: '600' }],
        'data-lg': ['16px', { lineHeight: '1.3', letterSpacing: '0.02em', fontWeight: '500' }],
        'data-md': ['13px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '500' }],
        'data-sm': ['11px', { lineHeight: '1.3', letterSpacing: '0.03em', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '4px',
        DEFAULT: '6px',
        md: '8px',
        lg: '8px',
        xl: '8px',
        full: '9999px',
      },
      spacing: {
        'space-1': '4px',
        'space-2': '8px',
        'space-3': '12px',
        'space-4': '16px',
        'space-5': '20px',
        'space-6': '24px',
        'space-8': '32px',
        'space-10': '40px',
        'space-12': '48px',
      },
      boxShadow: {
        sm: 'none',
        DEFAULT: 'none',
        lg: 'none',
        none: 'none',
        dropdown: 'var(--shadow-dropdown)',
        modal: 'var(--shadow-modal)',
        tooltip: 'var(--shadow-tooltip)',
      },
      keyframes: {
        'breathe': {
          '0%, 100%': { opacity: '0.7' },
          '50%': { opacity: '1' },
        },
      },
      animation: {
        'breathe': 'breathe 3s ease-in-out infinite',
      },
      transitionDuration: {
        'instant': '100ms',
        'fast': '150ms',
        'standard': '200ms',
        'slow': '300ms',
      },
      maxWidth: {
        'content': '1280px',
      },
    },
  },
  plugins: [],
};
