import { useEffect, useState } from 'react';
import { ChevronDown, ExternalLink, Scale } from 'lucide-react';
import { getFairness } from '../utils/api.js';

const REPORT_URL =
  'https://github.com/A-001-byte/Redrob-PMP/blob/main/submission/fairness_report.md';

function RatioRow({ row }) {
  const pct = Math.min(100, Math.max(2, row.impact_ratio * 100));
  const ok = !row.flagged;
  return (
    <div className="flex items-center gap-2 text-xs">
      <span className="w-44 shrink-0 truncate text-slate-400" title={row.group}>
        {row.group}
      </span>
      <div className="relative h-2.5 flex-1 overflow-hidden rounded-sm bg-muted">
        {/* four-fifths threshold marker */}
        <div className="absolute inset-y-0 left-[80%] w-px bg-slate-500/70" aria-hidden="true" />
        <div
          className={`h-full rounded-sm ${ok ? 'bg-emerald-500' : 'bg-amber-500'}`}
          style={{ width: `${pct}%` }}
        />
      </div>
      <span
        className={`w-12 shrink-0 text-right font-heading ${
          ok ? 'text-emerald-400' : 'text-amber-400'
        }`}
      >
        {row.impact_ratio.toFixed(3)}
      </span>
      <span className="hidden w-32 shrink-0 text-right text-slate-600 sm:inline">
        {row.top100_count}/100 · pool {row.pool_share_pct}%
      </span>
    </div>
  );
}

/** Read-only adverse-impact audit panel: impact ratios per proxy group vs
 *  the qualified pool, four-fifths threshold marked. Data from
 *  /api/fairness (generated by pipeline/fairness_audit.py). */
export default function FairnessPanel() {
  const [open, setOpen] = useState(false);
  const [report, setReport] = useState(null);
  const [error, setError] = useState(null);

  useEffect(() => {
    if (!open || report || error) return;
    getFairness()
      .then(setReport)
      .catch((e) => setError(String(e.message || e)));
  }, [open, report, error]);

  return (
    <section className="rounded-lg border border-border bg-surface">
      <button
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        className="flex w-full cursor-pointer items-center gap-2 px-4 py-3 text-left
                   transition-colors duration-150 hover:bg-surface-hover
                   focus:outline-none focus-visible:ring-2 focus-visible:ring-ring"
      >
        <Scale className="h-4 w-4 text-secondary" aria-hidden="true" />
        <span className="font-heading text-sm font-semibold text-foreground">
          Fairness Audit
        </span>
        <span className="hidden text-xs text-slate-500 sm:inline">
          adverse impact vs the qualified pool — four-fifths health-check
        </span>
        <ChevronDown
          className={`ml-auto h-4 w-4 text-slate-500 transition-transform duration-200 ${
            open ? 'rotate-180' : ''
          }`}
          aria-hidden="true"
        />
      </button>

      {open && (
        <div className="space-y-4 border-t border-border px-4 py-3">
          {error && (
            <p className="text-xs text-slate-500">
              {error.includes('404')
                ? 'Audit report not generated — run `python pipeline/fairness_audit.py`.'
                : `Could not load audit: ${error}`}
            </p>
          )}
          {!report && !error && (
            <div className="h-24 animate-pulse rounded-md bg-muted" />
          )}
          {report && (
            <>
              <p className="text-xs leading-relaxed text-slate-500">
                {report.disclaimer}{' '}
                <a
                  href={REPORT_URL}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-1 text-secondary hover:underline"
                >
                  View full report <ExternalLink className="h-3 w-3" aria-hidden="true" />
                </a>
              </p>
              <p className="text-xs text-slate-600">
                Qualified pool: {report.methodology.qualified_pool_count.toLocaleString()} of{' '}
                {report.methodology.total_candidates.toLocaleString()} (
                {report.methodology.qualified_pool_definition}). Bars show each group&apos;s
                impact ratio vs the best-selected group; the tick marks the 0.80 threshold —
                amber bars are flagged for review.
              </p>
              {report.attributes.map((attr) => (
                <div key={attr.attribute}>
                  <h4 className="mb-1.5 font-heading text-xs font-semibold uppercase tracking-wide text-slate-300">
                    {attr.attribute}
                  </h4>
                  <div className="space-y-1">
                    {attr.rows.map((r) => (
                      <RatioRow key={r.group} row={r} />
                    ))}
                  </div>
                </div>
              ))}
            </>
          )}
        </div>
      )}
    </section>
  );
}
